export const ANDROID_LIST_LOADING = 'ANDROID_LIST_LOADING';
export const ANDROID_LIST_LOADED = 'ANDROID_LIST_LOADED';
export const ANDROID_LIST_LOAD_FAIL = 'ANDROID_LIST_LOAD_FAIL';

export const INIT_LOADING = 'INIT_LOADING';
export const INIT_LOADED = 'INIT_LOADED';
export const INIT_LOAD_FAIL = 'INIT_LOAD_FAIL';

export const REQUEST_URL_LOADING = 'REQUEST_URL_LOADING';
export const REQUEST_URL_LOADED = 'REQUEST_URL_LOADED';
export const REQUEST_URL_LOAD_FAIL = 'REQUEST_URL_LOAD_FAIL';

export const FILE_EXPLORER_LOADING = 'FILE_EXPLORER_LOADING';
export const FILE_EXPLORER_LOADED = 'FILE_EXPLORER_LOADED';
export const FILE_EXPLORER_LOAD_FAIL = 'FILE_EXPLORER_LOAD_FAIL';

export const TEST_LIST_LOADING = 'TEST_LIST_LOADING';
export const TEST_LIST_LOADED = 'TEST_LIST_LOADED';
export const TEST_LIST_LOAD_FAIL = 'TEST_LIST_LOAD_FAIL';

export const TEST_REQUEST_LOADING = 'TEST_REQUEST_LOADING';
export const TEST_REQUEST_LOADED = 'TEST_REQUEST_LOADED';
export const TEST_REQUEST_LOAD_FAIL = 'TEST_REQUEST_LOAD_FAIL';
